package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Использование: go run reset.go <директория>")
		return
	}
	generate(os.Args[1])
}

func generate(root string) {
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedTypes | packages.NeedName | packages.NeedFiles,
		Dir:  root,
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		fmt.Printf("load error: %v\n", err)
		return
	}

	for _, pkg := range pkgs {
		processPkg(pkg)
	}
}

func processPkg(pkg *packages.Package) {
	var buf bytes.Buffer
	structs := []string{}
	var firstFile *ast.File

	for _, f := range pkg.Syntax {
		if firstFile == nil {
			firstFile = f
		}

		ast.Inspect(f, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return true
			}
			if ts.Doc == nil || !strings.Contains(ts.Doc.Text(), "generate:reset") {
				return true
			}

			structs = append(structs, ts.Name.Name)
			buf.WriteString(generateReset(ts.Name.Name, st))
			return true
		})
	}

	if buf.Len() == 0 {
		return
	}

	// Формируем файл
	out := &bytes.Buffer{}
	fmt.Fprintf(out, "// Code generated by reset. DO NOT EDIT.\n\npackage %s\n\n", pkg.Name)
	buf.WriteTo(out)

	// Форматируем
	src, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Printf("format error: %v\n", err)
		return
	}

	// Определяем директорию для записи
	if len(pkg.GoFiles) > 0 {
		dir := filepath.Dir(pkg.GoFiles[0])
		path := filepath.Join(dir, "reset.gen.go")
		os.WriteFile(path, src, 0644)
		fmt.Printf("generated: %s (%s)\n", path, strings.Join(structs, ", "))
	}
}

func generateReset(name string, st *ast.StructType) string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "func (x *%s) Reset() {\n", name)
	fmt.Fprintf(&buf, "\tif x == nil { return }\n")

	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue // пропускаем анонимные поля
		}
		for _, field := range f.Names {
			if !field.IsExported() {
				continue
			}
			fmt.Fprintf(&buf, "\tx.%s = ", field.Name)
			writeZero(&buf, f.Type)
			buf.WriteString("\n")
		}
	}
	buf.WriteString("}\n\n")
	return buf.String()
}

func writeZero(buf *bytes.Buffer, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			buf.WriteString(`""`)
		case "bool":
			buf.WriteString("false")
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64",
			"float32", "float64", "byte", "rune":
			buf.WriteString("0")
		default:
			buf.WriteString(t.Name + "{}")
		}
	case *ast.StarExpr:
		buf.WriteString("nil")
	case *ast.ArrayType:
		if t.Len == nil {
			buf.WriteString("nil")
		} else {
			// Для массивов с фиксированной длиной
			fmt.Fprintf(buf, "[%s]%s{}", t.Len, t.Elt)
		}
	case *ast.MapType:
		buf.WriteString("nil")
	case *ast.SelectorExpr:
		// Обработка time.Time и подобных
		if ident, ok := t.X.(*ast.Ident); ok {
			fmt.Fprintf(buf, "%s.%s{}", ident.Name, t.Sel.Name)
		} else {
			buf.WriteString("nil")
		}
	default:
		buf.WriteString("nil")
	}
}
